env:
  global:
    - secure: uWMR2V9VPdyjSzW9RgE/eHRN8Jw0ixFuK/TdqcofVN4vQIG3j32YGFCr0mLb8PDM1fZAMjPhY7NWgm2GqIR+xsPSgJR+sSuaSIY7WqZkla8RyfiE1yUi6NnTYvEMMIM5M7KmmdUI5kNC46F8yhnx0Gu7PKGhPyTVKqhhdpA352DQvKjda98nPsWpwra42nqu3Ewrj9P7JlcsqYY+LB5IPNchlClISld4e+LqMq/XA5HOmq610Nv4Ju/WdaRpwIogZnVyNXvri/97c2/Ym5GBeUSVK6JR3XY9t2FEdVzchbavR/wRjIMZXud191aoXzmjpxIlyLG/wU5L7QmI1EtMgENiPARQJJybRhdrJ7s29F2qrAgbyB8pryeej/dmrpK7o+6b0vuPvMOcLM3Fi1SBSl01fdsiabDYiKRjrRZN1jYvw87bGxF6IeVErrgPM+gLumH9xWZcI2x9+J3OBx5t/K8r6NJtM6HzsV7OutvGm79LJWhC/REA0EF+DHPaw4kdjV6v1v/JGj5EI1TiFASzRalY//FCRlucemhbRvGF1eVETrDQdvTdBoRIkq5jy3jB75WcIvobESHdZLwbDqhiizdXvv5Z0VAIbwqqdmaMURNxFvEJ23mZl3RKjOoeF0zw1A5km4Uz6uyR6TXMdsNgBBftKERDh7fZtiw5a7n7PNM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/The-Big-List-of-Hacked-Malware-Web-Sites
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - sudo apt-get -y install python3-pip python3-yaml
  - sudo apt-get -y install dos2unix
  - pip3 install colorama

script:
  - python3 ./update.py

notifications:
  email: false
