env:
  global:
    - secure: jkde/hiq5n7trKdi525KrJ0N1kIFkq/u027oU2+A6nhCsqwxTHLwTyjMaZ/ioVbqC1wvQxZsBrKm40gmTdqwgRj3KWizjZBRlotmoKcPy6AXhGKc6o+daZrrhtQy3Q3Uc5oEby/UH5MUkqUBia475/ErgWadmIWQ10SyQiDocMqXOLHFtqGJrMVSO6VrxAlVomnJ5ounEEDqSjIpLCcdeDY7lmJW/xwHMZLxYOP4OpSRJ04LX+3wl4mP1nHqZqwPbhQYAg6Z3xtZmwaSJUQ+P6u+gzPexFi99g9v7LS3VFo3D+ynY/myAzmHu8ho/DybbFnG3SDiKPC5ihMrDW55RfHeKWk+42FEzJspWc9KbbQAcfHfBH9ngHtJaGd9VJQdLRCDm1NNc6A2U66i32d78SXtZtu1uHlkTsJLwCuzj0sbGvfYxYmzSOysbj+yUGEsr9fIiw0/ckm7wld1YIGGur2yROrtjm+WCuACLTSF+EeLNWw4GBDCu4ENsghv5AdbCOI+3+OtDkpbddNjs/Z2OzMa4F5AM1b6WwhTay+FDWwtaZ9IcE+MLUrfPk/JpgTb8xfWdXLx7iiEbIw1CJEzq5FOGtJZjNUQ03sVuoy/sOfF+p1BH4bM0uJjHPrtRYE5jckyxRM/ATyCeKh+okIMz34aZaz4V7Zd15fTLmh/r8I=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/The-Big-List-of-Hacked-Malware-Web-Sites
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
