env:
  global:
    - secure: ruSD2rbSX4DqLZELO7wmwGfEPVqNSfBTNujvH1gxZLQg3UBxoKu5Mztn/xJwRGlRUb9FFOYQ6/PQtWkRXOSZOJxodeOWfCiCuWxNvEUmCdwwbB4w8oTMlEXcy+JUW03Q/EchHjbdLxaoK4EI67wSF49cTxp0I1J6qsNnVGTXI0b33QYfFtPQ4PA7PF5N68VGckFSbafT2UspAHG4OfkH4lzntgk+jSCEIDcnP7KaErERlQkmT/j43IcKAEuMKfrtyYRccf0Tdm7T5PvMkfezE8LE0IAK9aMKOcWwRA3JFXU8dSQdpPKaRLkk+9U1uxHz7esEtm+CiG9NwN9Gyzh+rqsnz22vR0u8fbTvPSpCVY2SLJfBkq8NXxbPfkDr2JXJNL5d9F88lo0zpnGI6l/E36hO6BsuObqRjc7tTKuBA4bV0lIIB8mCJqyous8auRrbwXjljDvK6AlYcX810YwINossY3wILB1XCcconwi4L1YejXzhZZRKns/r72CONNys/QnYin/5h1aGw1aNK/mv/ZCDBg2Y+AA9o9rjwOqysVcjgAGZft6vQmnac7p2BuNM+1TzkZg/DhEH1fJqprfWPQhRD/ScSLgJNYkxZHfgVGZ/IqfEnRd7J1lkPDD+ove85tkjUq1FKCiBGsZQ0lCTmQ+ogIaFl7WAiVgrtj3JWqY=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/The-Big-List-of-Hacked-Malware-Web-Sites
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
