env:
  global:
    - secure: aDEVcgOVLlrLLXB5zQlQhpEtEu2Fy+gCsololZwRNWRB5SfmKbPASfH/h4gHb6AE0l/+gV+W4WRirPYsTok+yYQcteIRMRXtauqyyE1KpmN62nFqXLrshH3Y3Taz7iVex1ryDCf6IAIeanBXs1P8bmmvhoEp+qn0PFrvhGiK3WwJwfJiffWvnFasNTx1h1njXfHugXXITCCLT9YmYTB1SD1B2yWkpfkmb4Dsm41O8AfvWPljgjD0AQ93QAJW7xdPeBvgWTnhMtNIXJYACR4XMc+HhXC5hNKpWlonaUQiufAffCD/QME/jk/+/w/iNgMFLWFuAL2rYUqTSFSM3Npz/VDbrs5oWSFKA/NnvAAXGSQ29kOsKsupwtetJoldFNDhTux+yBprwFCbbLKYvu+fbSy1Rg/N+fk1lGBqWxYNeBfewjat9lccfgbUdYO5n4EC+NskqY+EYTEiLxqN70gQEHXNXAVi3pAWzZ66bJ3p9Js1Ozc+MIKiWU6TzUkXP6yr7lxtWCbdAGoFjTkQFYu9Pecn/CuTYFmbDkpoIfsEZ9FHJUglDhDEPegqkL3abEXzEeG+yPymsAJ8qM+aOffAsImjHCy15G+FAWNq5LzVH+L2aY8kcMGHJSSAGywVDkAqqLvOnsbKASd74zuRVV3ovUvi1o9pPAemuQoN5hJTPJM=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/The-Big-List-of-Hacked-Malware-Web-Sites
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
