addons:
    apt:
        packages:
        - dos2unix
cache:
- pip
dist: xenial
env:
    global:
    -   secure: CGa1A3du/mCuGlwpz++zJ55o8nE7biq0Z2s+IQcF0PLyutDDUzzlu4LoTb812QGIntgohdgp1FI9wWRPoTh8t6YCD8ILDxMTI8xnuB12kYwa7hUan0osUg8GiG+XUyLMQqfbK4JcY9I/FCKDRuOD2as7NOFLLyKE5Rwjahcd/4tqc+HHJRNczveqm9GYS3+uXUHtIWf+TtPYFAGeecmsJ9gHz1Szbft+HoH7FeM9VHeSMZd13ldfybIawGCEz0vD2nfs0jkz+GqFPAhEDZ/TIs2vsRRYwvOjbZC6x4CQbf/Sa8SQoVMUmTbjuMDF9dK9tVxElNj6W2mGIsfsCmPe8cOHVMCmw38gts2+mzDOfkCVsJgYh3AdtoxgDmBjZGX8/Isu8GJoVtYp2DISLMXsJqGSNAekEr4tZRz2BCwHA2cDi6OiGVRoaYpv9viHC/Hx3SCbgaxneiMH1p5G9xv6cTIutO3BfVT4hOYx/Cnpuzhegka2rqzXuECImIeY5yI22Fe3zK3briVhHW1BzdLUDmSMXVd0Myi4fd/l9RiCGxZSv6ufju1KalyZhaTjlYp0eqN4zjZJ+58w3KkLY39XR9rYsKf1fMEb/J0ioV2h8VXXCe56TpCPW4J23tXV1i1LeY8uUu/jODUi2Zk1/7PKf01I1IqYtxOcMADp+XYLqs8=
    -   GIT_NAME: Travis CI
    -   GIT_EMAIL: dead-hosts@funilrys.com
    -   TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/The-Big-List-of-Hacked-Malware-Web-Sites
    -   GIT_BRANCH: master
    -   UPDATE_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/update.py
    -   ADMINISTATION_LOCATION: https://raw.githubusercontent.com/Ultimate-Hosts-Blacklist/repository-structure/master/administration.py
install:
- pip3 install --upgrade pip
- pip3 install ultimate-hosts-blacklist-input-repo-updater
language: python
matrix:
    fast_finish: true
notifications:
    email:
        on_failure: always
        on_success: never
        recipients:
        - dead-hosts@funilrys.com
        - mitchellkrogza+ultimatehostsblacklist@gmail.com
python:
- '3.7'
script:
- ultimate-hosts-blacklist-input-repo-updater --version
- ultimate-hosts-blacklist-input-repo-updater -m
sudo: required
