env:
  global:
    - secure: P1dXNIoSvnXwIXG+zstTv0ifDIpGrRBfcUbcEeUo2VGqs5Wy7Dy+ZzvuuR65Fsofx4TWKjDiJ5WftQZmc0F5F5BShyWd2Z9F4jO9WaNzwctbnMSxNCrcWR4PF/6Lg9UC6BBewq/DQIt5wNp1HlEZ2lboaxYdsxSzpU0LxO1W9mrSdftc8N01w1OfarcXKDY0+AeliAlh4tXbMUZQY360FIuh7ljbrOsl7Xoh0Ywx39Xvnkd19kSf0MkKyVhxnE+3gbZWpntOiaZ+L2kAS5sUDg7K8zKIH2deWBN5z9riDfn0xleg/E8K/0zsNGG+KZL7QObfxf2ep98XRUFB7ndV0ga5FMaPPlBLXC9Tljce/jQjJ2ngFdd7L9NeNp70r9JcTev4e1M+1iqJDpOqeovWe8cdwnlr+w+ZAodKMIY9Xk5GQ1bVRaG3JRorW1fooJYpUYwHHO35J9HeDEQ/SG4GrAnaYJmizAQR3GKy0yR/P87cy0xtEU5B+sEdui39qMgdA+fiiKPbPkD6Q/K5ijbNZ2bz1HAOZN2jF/w1h3Ok/3GFY1tglOgANxyHZZOEMYg3+28B/Tx373v+qd6BeBJGBQ4xCQWjup0detUVPWwAq66RnQthx9yZV+fJyPjUCaIftShhfk5iUUBEBHSXd0q1H9fdvDpsrQVNIko50hH5y/E=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/The-Big-List-of-Hacked-Malware-Web-Sites
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
